### ISSUE TITLE
Certains mots de passe ne fonctionnent pas

### ISSUE THREAD

**Issue by arno-github** [Mer0me/MonnaieM#4]
Bonjour
Je me suis inscrit hier sur Monnaie M, et il m'était impossible de me connecter. J'ai demandé à réinitialiser mon mot de passe, et depuis, avec un nouveau, ça passe. Je suspecte certains caractères de ne pas être correctement échappés, et en particulier l'apostrophe. Je n'ai malheureusement pas noté mon ancien mot de passe, mais je sais qu'il en contenait 2.

**Comment by utilisezlinux** [comment]
Bonjour Arno,
ton problème a-t-il été réglé?

**Comment by githare** [comment]
Bonjour
Je ne me rappelais même plus de ce commentaire... Je n'utilise pas Monnaie M tous les jours, mais comme j'ai réalisé une transaction il y a peu, je pense pouvoir dire que je n'ai pas de problème de connexion ! Mais ça ne veut pas dire qu'il n'y a pas de problème avec les apostrophes dans les mots de passe ; il faudrait tester !

**Comment by ghost** [comment]
Ok, j'essayerai de penser à vérifier ça…
